name: Continuous Integration

on:
  push:
    branches: [ master, CI-workflow ]
  pull_request:
    branches: [ master ]

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: testResult.json
          path: ./testResult.json
  download:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/download-artifact@v2
        with:
          name: testResult.json
      - run: cat testResult.json    
